### ISSUE TITLE
Bug: Client-side error when viewing NFT page

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/web-core#5] opened 2022-11-21 19:18 UTC
_Copying bug reported by @douglasqian on Telegram_

> [I] run into this error when I try to look at "NFTs"

![Image](https://user-images.githubusercontent.com/46296830/203140681-5e96e013-9098-498b-91d9-afdc60d2c483.jpg)

**Comment by martinvol** [comment] 2022-12-05 14:00
I am not able to reproduce this in my development local and the errors in production are not useful because they are minified, not sure were to go from here

**Comment by nicolasbrugneaux** [comment] 2022-12-07 15:35
Fixed in 3cfee318

**Closed as completed by nicolasbrugneaux** 2022-12-07 15:35 UTC

**Comment by arthurgousset** [comment] 2022-12-07 16:34
Context: 
- Easy bug, was blocked by issue with compiling

**Comment by nicolasbrugneaux** [comment] 2022-12-07 16:35
More info on the compile error here: https://github.com/celo-org/web-core/issues/6
